name:                LogicalFormulas
version:             0.1.0.0
github:              "furtiveJack/LogicalFormulas"
license:             BSD3
author:              "ttraina - rmarszal"
maintainer:          "ttraina@etud.u-pem.fr"
copyright:           "2020 ttraina - rmarszal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/furtiveJack/LogicalFormulas#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  LogicalFormulas-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LogicalFormulas

tests:
  LogicalFormulas-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LogicalFormulas
